/* curve25519_gf32.h - GENERATED by tools/gen_gf32.py, do not edit.
 * Multiply / square for 16 x 16-bit limbs (radix 2^16) using only
 * 32x32->32 multiplies. See gen_gf32.py for the layout choices. */

/* Row-wise schoolbook. With 16-bit limbs r + a*b + carry never exceeds
 * 2^32 - 1 ((2^16-1)^2 + 2*(2^16-1) = 2^32-1), so a plain 32-bit MLA and
 * a running carry do the whole job: no 64-bit accumulator, and the code
 * is ~0.5 KB instead of 5 KB, which matters for the ARM710's 8 KB cache. */
static void gf_mul_raw(gfl r[32], const gfl a[16], const gfl b[16])
{
  int i;
  gfl ai, c, t;
  for (i = 0; i < 16; i++) r[i] = 0;
  for (i = 0; i < 16; i++) {
    ai = a[i]; c = 0;
    t = r[i] + ai*b[0]; r[i] = t & 0xffff; c = t >> 16;
    t = r[i+1] + ai*b[1] + c; r[i+1] = t & 0xffff; c = t >> 16;
    t = r[i+2] + ai*b[2] + c; r[i+2] = t & 0xffff; c = t >> 16;
    t = r[i+3] + ai*b[3] + c; r[i+3] = t & 0xffff; c = t >> 16;
    t = r[i+4] + ai*b[4] + c; r[i+4] = t & 0xffff; c = t >> 16;
    t = r[i+5] + ai*b[5] + c; r[i+5] = t & 0xffff; c = t >> 16;
    t = r[i+6] + ai*b[6] + c; r[i+6] = t & 0xffff; c = t >> 16;
    t = r[i+7] + ai*b[7] + c; r[i+7] = t & 0xffff; c = t >> 16;
    t = r[i+8] + ai*b[8] + c; r[i+8] = t & 0xffff; c = t >> 16;
    t = r[i+9] + ai*b[9] + c; r[i+9] = t & 0xffff; c = t >> 16;
    t = r[i+10] + ai*b[10] + c; r[i+10] = t & 0xffff; c = t >> 16;
    t = r[i+11] + ai*b[11] + c; r[i+11] = t & 0xffff; c = t >> 16;
    t = r[i+12] + ai*b[12] + c; r[i+12] = t & 0xffff; c = t >> 16;
    t = r[i+13] + ai*b[13] + c; r[i+13] = t & 0xffff; c = t >> 16;
    t = r[i+14] + ai*b[14] + c; r[i+14] = t & 0xffff; c = t >> 16;
    t = r[i+15] + ai*b[15] + c; r[i+15] = t & 0xffff; c = t >> 16;
    r[i+16] = c;
  }
}

/* r[0..31] = a * a: cross products a[i]*a[j] (i<j) are accumulated once,
 * the whole result is doubled, then the squares are added with carry. */
static void gf_sqr_raw(gfl r[32], const gfl a[16])
{
  int i;
  gfl ai, c, t;
  for (i = 0; i < 32; i++) r[i] = 0;
  for (i = 0; i < 15; i++) {
    ai = a[i]; c = 0;
    switch (i) {
    case 0:
      t = r[i+1] + ai*a[1] + c; r[i+1] = t & 0xffff; c = t >> 16;
    case 1:
      t = r[i+2] + ai*a[2] + c; r[i+2] = t & 0xffff; c = t >> 16;
    case 2:
      t = r[i+3] + ai*a[3] + c; r[i+3] = t & 0xffff; c = t >> 16;
    case 3:
      t = r[i+4] + ai*a[4] + c; r[i+4] = t & 0xffff; c = t >> 16;
    case 4:
      t = r[i+5] + ai*a[5] + c; r[i+5] = t & 0xffff; c = t >> 16;
    case 5:
      t = r[i+6] + ai*a[6] + c; r[i+6] = t & 0xffff; c = t >> 16;
    case 6:
      t = r[i+7] + ai*a[7] + c; r[i+7] = t & 0xffff; c = t >> 16;
    case 7:
      t = r[i+8] + ai*a[8] + c; r[i+8] = t & 0xffff; c = t >> 16;
    case 8:
      t = r[i+9] + ai*a[9] + c; r[i+9] = t & 0xffff; c = t >> 16;
    case 9:
      t = r[i+10] + ai*a[10] + c; r[i+10] = t & 0xffff; c = t >> 16;
    case 10:
      t = r[i+11] + ai*a[11] + c; r[i+11] = t & 0xffff; c = t >> 16;
    case 11:
      t = r[i+12] + ai*a[12] + c; r[i+12] = t & 0xffff; c = t >> 16;
    case 12:
      t = r[i+13] + ai*a[13] + c; r[i+13] = t & 0xffff; c = t >> 16;
    case 13:
      t = r[i+14] + ai*a[14] + c; r[i+14] = t & 0xffff; c = t >> 16;
    case 14:
      t = r[i+15] + ai*a[15] + c; r[i+15] = t & 0xffff; c = t >> 16;
    }
    r[i+16] = c;
  }
  c = 0;
  for (i = 0; i < 32; i++) { t = (r[i] << 1) | c; r[i] = t & 0xffff; c = t >> 16; }
  c = 0;
  for (i = 0; i < 16; i++) {
    t = r[2*i] + a[i]*a[i] + c; r[2*i] = t & 0xffff; c = t >> 16;
    t = r[2*i+1] + c; r[2*i+1] = t & 0xffff; c = t >> 16;
  }
}
