; Atom modem: Psion-tuned WiFi modem firmware for the M5Stack Atom (Lite or
; Matrix) on an Atomic RS232 Base. MIT licence (see LICENSE at the top of
; the repository).
;   pio run                 build
;   pio run -t upload       build and flash over USB
;   pio device monitor      the USB console (status messages, 115200 baud)
; The host tests are in hosttest/ (make -C hosttest test).

[env:m5stack-atom]
platform = espressif32@6.9.0
board = m5stack-atom
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra -Wno-unused-parameter
