#!/usr/bin/env python3
"""Generates db/src/curve25519_gf32.h: field multiplication/squaring mod
2^255-19 for 32-bit CPUs with only a 32x32->32 multiply (ARM7/ARM710).

Representation: 16 unsigned limbs of 16 bits each held in 32-bit words
(radix 2^16), so every product is one 32-bit MUL/MLA.

Two layouts: "rows" (default) is a row-wise schoolbook with a running
32-bit carry, ~0.5 KB of code, best once the ARM710's 8 KB cache is taken
into account; "comba" is a fully unrolled column-wise version with (lo,hi)
accumulators, ~15% fewer core cycles but 8 KB of code that thrashes the
cache (emu/run_psissh.py --bench --count --cache shows the difference).

Run: python3 tools/gen_gf32.py [rows|comba] > db/src/curve25519_gf32.h"""

N = 16
out = []
w = out.append

w("/* curve25519_gf32.h - GENERATED by tools/gen_gf32.py, do not edit.")
w(" * Multiply / square for 16 x 16-bit limbs (radix 2^16) using only")
w(" * 32x32->32 multiplies. See gen_gf32.py for the layout choices. */")
w("")
MODE = "rows"   # "rows": compact row-wise (default); "comba": fully unrolled columns
import sys
if len(sys.argv) > 1: MODE = sys.argv[1]

if MODE == "rows":
    w("/* Row-wise schoolbook. With 16-bit limbs r + a*b + carry never exceeds")
    w(" * 2^32 - 1 ((2^16-1)^2 + 2*(2^16-1) = 2^32-1), so a plain 32-bit MLA and")
    w(" * a running carry do the whole job: no 64-bit accumulator, and the code")
    w(" * is ~0.5 KB instead of 5 KB, which matters for the ARM710's 8 KB cache. */")
    w("static void gf_mul_raw(gfl r[32], const gfl a[16], const gfl b[16])")
    w("{")
    w("  int i;")
    w("  gfl ai, c, t;")
    w("  for (i = 0; i < 16; i++) r[i] = 0;")
    w("  for (i = 0; i < 16; i++) {")
    w("    ai = a[i]; c = 0;")
    for j in range(N):
        if j == 0:
            w("    t = r[i] + ai*b[0]; r[i] = t & 0xffff; c = t >> 16;")
        else:
            w("    t = r[i+%d] + ai*b[%d] + c; r[i+%d] = t & 0xffff; c = t >> 16;" % (j, j, j))
    w("    r[i+16] = c;")
    w("  }")
    w("}")
    w("")
    w("/* r[0..31] = a * a: cross products a[i]*a[j] (i<j) are accumulated once,")
    w(" * the whole result is doubled, then the squares are added with carry. */")
    w("static void gf_sqr_raw(gfl r[32], const gfl a[16])")
    w("{")
    w("  int i;")
    w("  gfl ai, c, t;")
    w("  for (i = 0; i < 32; i++) r[i] = 0;")
    w("  for (i = 0; i < 15; i++) {")
    w("    ai = a[i]; c = 0;")
    w("    switch (i) {")
    # for row i, j runs i+1..15: emit a switch with fallthrough so each row's
    # unrolled tail is shared (Duff-style), j-indexed by absolute position
    for j in range(1, N):
        w("    case %d:" % (j - 1))
        w("      t = r[i+%d] + ai*a[%d] + c; r[i+%d] = t & 0xffff; c = t >> 16;" % (j, j, j))
    w("    }")
    w("    r[i+16] = c;")
    w("  }")
    w("  c = 0;")
    w("  for (i = 0; i < 32; i++) { t = (r[i] << 1) | c; r[i] = t & 0xffff; c = t >> 16; }")
    w("  c = 0;")
    w("  for (i = 0; i < 16; i++) {")
    w("    t = r[2*i] + a[i]*a[i] + c; r[2*i] = t & 0xffff; c = t >> 16;")
    w("    t = r[2*i+1] + c; r[2*i+1] = t & 0xffff; c = t >> 16;")
    w("  }")
    w("}")
    print("\n".join(out))
    sys.exit(0)

w("/* r[0..31] = a * b as 32 limbs of 16 bits (r[31] < 2^16). The column")
w(" * accumulator is an explicit (lo,hi) word pair: GCC 3.0 spills a 64-bit")
w(" * variable at every column boundary but keeps two words in registers. */")
w("static void gf_mul_raw(gfl r[32], const gfl a[16], const gfl b[16])")
w("{")
w("  gfl lo, hi, p;")
first = True
for k in range(2 * N - 1):
    terms = []
    for i in range(N):
        j = k - i
        if 0 <= j < N:
            terms.append("a[%d]*b[%d]" % (i, j))
    if first:
        w("  lo = %s; hi = 0;" % terms[0])
        terms = terms[1:]
        first = False
    for tm in terms:
        w("  p = %s; lo += p; hi += (lo < p);" % tm)
    w("  r[%d] = lo & 0xffff; lo = (lo >> 16) | (hi << 16); hi >>= 16;" % k)
w("  r[%d] = lo;" % (2 * N - 1))
w("}")
w("")
w("/* r[0..31] = a * a: cross products are summed once and doubled */")
w("static void gf_sqr_raw(gfl r[32], const gfl a[16])")
w("{")
w("  gfl lo, hi, sl, sh, p;")
w("  lo = 0; hi = 0;")
for k in range(2 * N - 1):
    cross = []
    for i in range(N):
        j = k - i
        if i < j < N:
            cross.append("a[%d]*a[%d]" % (i, j))
    if cross:
        w("  sl = %s; sh = 0;" % cross[0])
        for tm in cross[1:]:
            w("  p = %s; sl += p; sh += (sl < p);" % tm)
        w("  sh = (sh << 1) | (sl >> 31); sl <<= 1;")
        w("  lo += sl; hi += sh + (lo < sl);")
    if k % 2 == 0:
        w("  p = a[%d]*a[%d]; lo += p; hi += (lo < p);" % (k // 2, k // 2))
    w("  r[%d] = lo & 0xffff; lo = (lo >> 16) | (hi << 16); hi >>= 16;" % k)
w("  r[%d] = lo;" % (2 * N - 1))
w("}")
print("\n".join(out))
