#!/usr/bin/env python3
"""PsiWeb's toolbar pictures (original pixel art, in the spirit of the
Psion's own programs) -> BMP files for bmconv, and app/pwicons.h with
their ids. As mail/tools/mkicons.py.

    web/tools/mkicons.py OUTDIR HEADER

Each picture is 24x20 ASCII art: k black, d dark grey, l light grey,
w white, . transparent. Every picture gets a 1-bit mask right after it in
the MBM (black = drawn), so ids go picture, mask, picture, mask...
"""
import sys, os
from PIL import Image

GREY = {'k': 0, 'd': 85, 'l': 170, 'w': 255, '.': 255}

ICONS = [
# Open address: a globe
('ToolOpen', """
........kkkkkkkk........
......kkwwwwkwwwkk......
.....kwwwwwwkwwwwwk.....
....kwwwwwwwkwwwwwwk....
...kwwwwwwwwkwwwwwwwk...
...kwwwkwwwwkwwwwkwwk...
..kwwwwwkkkkkkkkkwwwwk..
..kwwwwwwwwwkwwwwwwwwk..
..kwwwwwwwwwkwwwwwwwwk..
..kkkkkkkkkkkkkkkkkkkk..
..kwwwwwwwwwkwwwwwwwwk..
..kwwwwwwwwwkwwwwwwwwk..
..kwwwwwkkkkkkkkkwwwwk..
...kwwwkwwwwkwwwwkwwk...
...kwwwwwwwwkwwwwwwwk...
....kwwwwwwwkwwwwwwk....
.....kwwwwwwkwwwwwk.....
......kkwwwwkwwwkk......
........kkkkkkkk........
........................
"""),
# Back: an arrow to the left
('ToolBack', """
........................
........................
.......k................
......kk................
.....kwk................
....kwwkkkkkkkkkkkkkk...
...kwwwwwwwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwk...
.kwwwwwwwwwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwk...
...kwwwwwwwwwwwwwwwwk...
....kwwkkkkkkkkkkkkkk...
.....kwk................
......kk................
.......k................
........................
........................
........................
........................
........................
"""),
# Home page: a house
('ToolHome', """
...........kk...........
..........kwwk..........
.........kwwwwk.........
........kwwwwwwk........
.......kwwwwwwwwk.......
......kwwwwwwwwwwk......
.....kwwwwwwwwwwwwk.....
....kwwwwwwwwwwwwwwk....
...kwwwwwwwwwwwwwwwwk...
..kkkkwwwwwwwwwwwwkkkk..
.....kwwwwwwwwwwwwk.....
.....kwwkkkwwwkkkwk.....
.....kwwkwkwwwkwkwk.....
.....kwwkkkwwwkkkwk.....
.....kwwwwwwwwwwwwk.....
.....kwwwwwkkkkwwwk.....
.....kwwwwwkwwkwwwk.....
.....kwwwwwkwwkwwwk.....
.....kkkkkkkkkkkkkk.....
........................
"""),
# Zoom: a magnifying glass
('ToolZoom', """
......kkkkkk............
....kkwwwwwwkk..........
...kwwwwwwwwwwk.........
..kwwwwwkkwwwwwk........
..kwwwwwkkwwwwwk........
.kwwwwwwkkwwwwwwk.......
.kwwwkkkkkkkkwwwk.......
.kwwwkkkkkkkkwwwk.......
.kwwwwwwkkwwwwwwk.......
..kwwwwwkkwwwwwk........
..kwwwwwkkwwwwwk........
...kwwwwwwwwwwkk........
....kkwwwwwwkkdkk.......
......kkkkkk.kddkk......
..............kddkk.....
...............kddkk....
................kddkk...
.................kddk...
..................kkk...
........................
"""),
]


def parse(art):
    rows = [r for r in art.strip('\n').split('\n')]
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, '.') for r in rows]
    return rows, w, len(rows)


def main():
    out, header = sys.argv[1], sys.argv[2]
    os.makedirs(out, exist_ok=True)
    files = []
    ids = []
    for name, art in ICONS:
        rows, w, h = parse(art)
        if (w, h) != (24, 20):
            raise SystemExit(f'{name}: {w}x{h}, toolbar pictures are 24x20')
        img = Image.new('L', (w, h), 255)
        mask = Image.new('1', (w, h), 1)
        for y, r in enumerate(rows):
            for x, c in enumerate(r):
                if c not in GREY:
                    raise SystemExit(f'{name}: bad pixel {c!r}')
                img.putpixel((x, y), GREY[c])
                if c != '.':
                    mask.putpixel((x, y), 0)
        fi = os.path.join(out, f'{name}.bmp')
        fm = os.path.join(out, f'{name}_m.bmp')
        img.convert('RGB').save(fi)
        mask.convert('RGB').save(fm)
        files += [fi, fm]
        ids.append(name)
    with open(header, 'w') as f:
        f.write('/* pwicons.h - made by web/tools/mkicons.py: PsiWeb.mbm ids */\n')
        f.write('#ifndef PWICONS_H\n#define PWICONS_H\nenum TPwIconId\n\t{\n')
        for i, n in enumerate(ids):
            f.write(f'\tEMbm{n} = {2 * i}, EMbm{n}Mask = {2 * i + 1},\n')
        f.write(f'\tEMbmCount = {2 * len(ids)}\n\t}};\n#endif\n')
    with open(os.path.join(out, 'files.txt'), 'w') as f:
        for i, p in enumerate(files):
            f.write(('/2' if i % 2 == 0 else '/1') + os.path.basename(p) + '\n')


if __name__ == '__main__':
    main()
