#!/usr/bin/env python3
"""gen_chacha.py - writes chacha_arm.h: the ChaCha20 block function
(RFC 8439) in ARM assembler for the Psion's ARM710, used by web/tls/aead.c.

    python3 web/tls/gen_chacha.py > web/tls/chacha_arm.h

    void tls_chacha_block(unsigned int out[16], const unsigned int in[16])
    out = the 20 rounds of in, plus in

Rows a (x0-x3), b (x4-x7) and d (x12-x15) stay in r0-r11, x10 in r12 and
x11 in lr; x8 and x9 live on the stack. The rotations cost nothing: ARM can
rotate the second operand of any instruction, so after "b ^= c" b is kept
unrotated and the rotation is applied where b is next used ("lazy"
rotation). A quarter round is then 8 instructions (plus a load and store
for x8 or x9): about 1,000 instructions a 64-byte block, against about
2,600 for libtomcrypt's C on this compiler.
"""
QR_COL = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15)]
QR_DIAG = [(0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]
REG = {i: "r%d" % i for i in range(8)}
REG.update({12: "r8", 13: "r9", 14: "r10", 15: "r11", 10: "r12", 11: "lr"})
MEM = {8: "[sp, #0]", 9: "[sp, #4]"}

rot = {i: 0 for i in range(16)}     # pending left rotation of each word

def op2(i):
    r = rot[i]
    return REG[i] if r == 0 else "%s, ror #%d" % (REG[i], 32 - r)

L = []
def qr(a, b, c, d):
    inmem = c in MEM
    C = "r12" if c == 10 else "lr" if c == 11 else None
    if inmem:
        # x8/x9 go through a register freed for the moment: use the
        # scratch slot of a (none free), so load into lr after saving x11
        pass
    steps = [(16, 12), (8, 7)]
    if inmem:
        L.append("str lr, [sp, #8]")          # park x11
        L.append("ldr lr, %s" % MEM[c])
        C = "lr"
    for rd, rb in steps:
        L.append("add %s, %s, %s" % (REG[a], REG[a], op2(b)))     # a += b
        L.append("eor %s, %s, %s" % (REG[d], REG[a], op2(d)))     # d ^= a
        rot[d] = rd
        L.append("add %s, %s, %s" % (C, C, op2(d)))               # c += d
        L.append("eor %s, %s, %s" % (REG[b], C, op2(b)))          # b ^= c
        rot[b] = rb
    if inmem:
        L.append("str lr, %s" % MEM[c])
        L.append("ldr lr, [sp, #8]")

L.append("stmfd sp!, {r0, r1, r4, r5, r6, r7, r8, r9, r10, r11, lr}")
L.append("sub sp, sp, #12")                   # x8, x9, x11 parked
# [sp+12] = out, [sp+16] = in
L.append("mov r12, r1")
L.append("ldr r0, [r12, #32]")
L.append("str r0, [sp, #0]")
L.append("ldr r0, [r12, #36]")
L.append("str r0, [sp, #4]")
L.append("add r0, r12, #16")
L.append("ldmia r0, {r4, r5, r6, r7}")
L.append("add r0, r12, #48")
L.append("ldmia r0, {r8, r9, r10, r11}")
L.append("ldr lr, [r12, #44]")
L.append("ldmia r12, {r0, r1, r2, r3}")
L.append("ldr r12, [r12, #40]")
for rnd in range(10):
    for q in QR_COL:
        qr(*q)
    for q in QR_DIAG:
        qr(*q)
# feed forward: x[i] += in[i]
L.append("str r12, [sp, #8]")                 # x10 (x11 stays in lr for now)
L.append("str lr, [sp, #-4]!")                # x11 below: offsets now +4
# stack now: [sp]=x11, [sp+4]=x8, [sp+8]=x9, [sp+12]=x10, [sp+16]=out, [sp+20]=in
L.append("ldr r12, [sp, #20]")
for i in list(range(8)) + [12, 13, 14, 15]:
    L.append("ldr lr, [r12, #%d]" % (4 * i))
    L.append("add %s, lr, %s" % (REG[i], op2(i)))
L.append("ldr r12, [sp, #16]")
L.append("stmia r12, {r0, r1, r2, r3}")
L.append("add lr, r12, #16")
L.append("stmia lr, {r4, r5, r6, r7}")
L.append("add lr, r12, #48")
L.append("stmia lr, {r8, r9, r10, r11}")
L.append("ldr r0, [sp, #4]")                  # x8
L.append("ldr r1, [sp, #8]")                  # x9
L.append("ldr r2, [sp, #12]")                 # x10
L.append("ldr r3, [sp, #0]")                  # x11
L.append("ldr lr, [sp, #20]")
L.append("add lr, lr, #32")
L.append("ldmia lr, {r4, r5, r6, r7}")
L.append("add r0, r0, r4")
L.append("add r1, r1, r5")
L.append("add r2, r2, r6")
L.append("add r3, r3, r7")
L.append("add lr, r12, #32")
L.append("stmia lr, {r0, r1, r2, r3}")
L.append("add sp, sp, #16")
L.append("ldmfd sp!, {r0, r1, r4, r5, r6, r7, r8, r9, r10, r11, pc}")

out = ["/* chacha_arm.h - GENERATED by web/tls/gen_chacha.py, do not edit. */",
       "__asm__(",
       '  "\\t.text\\n"',
       '  "\\t.align 2\\n"',
       '  "\\t.global tls_chacha_block\\n"',
       '  "tls_chacha_block:\\n"']
for l in L:
    out.append('  "\\t%s\\n"' % l)
out.append(");")
print("\n".join(out))

# ---------------------------------------------------------------- Poly1305
# void tls_poly_mul(unsigned int h[10], const unsigned int T[19])
# h = h * r mod 2^130 - 5, with h and r in 13-bit limbs (h loose: a limb
# may be up to 2^14 + 2^9 after the message is added). T[j] (j = k-i+9) is
# r[j-9] for j >= 9 and 5*r[j+1] below. h stays in r2-r11; each column is
# summed in two halves (i = 0..4 and 5..9: each below 2^32, the whole could
# overflow), stored, then carried.
P = []
P.append("stmfd sp!, {r0, r4, r5, r6, r7, r8, r9, r10, r11, lr}")
P.append("sub sp, sp, #80")                   # A[10] at sp, B[10] at sp+40; h ptr at sp+80
P.append("ldmia r0, {r2, r3, r4, r5, r6, r7, r8, r9, r10, r11}")
HR = ["r%d" % (2 + i) for i in range(10)]
for k in range(10):
    for half in (0, 1):
        acc = "r0" if half == 0 else "r12"
        first = True
        for i in range(5 * half, 5 * half + 5):
            P.append("ldr lr, [r1, #%d]" % (4 * (k - i + 9)))
            if first:
                P.append("mul %s, %s, lr" % (acc, HR[i]))
                first = False
            else:
                P.append("mla %s, %s, lr, %s" % (acc, HR[i], acc))
    P.append("str r0, [sp, #%d]" % (4 * k))
    P.append("str r12, [sp, #%d]" % (40 + 4 * k))
# carry: r11 mask, r10 h ptr, r9 carry
P.append("ldr r10, [sp, #80]")
P.append("mov r11, #0x1f00")
P.append("orr r11, r11, #0xff")
P.append("mov r9, #0")
for k in range(10):
    P.append("ldr r2, [sp, #%d]" % (4 * k))
    P.append("ldr r3, [sp, #%d]" % (40 + 4 * k))
    P.append("and r4, r2, r11")
    P.append("and r5, r3, r11")
    P.append("add r4, r4, r5")
    P.append("add r4, r4, r9")
    P.append("and r5, r4, r11")
    P.append("str r5, [r10, #%d]" % (4 * k))
    P.append("mov r9, r2, lsr #13")
    P.append("add r9, r9, r3, lsr #13")
    P.append("add r9, r9, r4, lsr #13")
# 2^130 = 5: the carry out times 5 into limbs 0 and 1
P.append("add r9, r9, r9, lsl #2")
P.append("ldr r2, [r10, #0]")
P.append("add r2, r2, r9")
P.append("and r3, r2, r11")
P.append("str r3, [r10, #0]")
P.append("ldr r3, [r10, #4]")
P.append("add r3, r3, r2, lsr #13")
P.append("str r3, [r10, #4]")
P.append("add sp, sp, #80")
P.append("ldmfd sp!, {r0, r4, r5, r6, r7, r8, r9, r10, r11, pc}")

out = ["__asm__(",
       '  "\\t.text\\n"',
       '  "\\t.align 2\\n"',
       '  "\\t.global tls_poly_mul\\n"',
       '  "tls_poly_mul:\\n"']
for l in P:
    out.append('  "\\t%s\\n"' % l)
out.append(");")
print("\n".join(out))
