#!/usr/bin/env python3
"""mkres.py - compiles PsiWeb's resources into psiweb.exe (pwres.c)

EPOC paths ("D:\\System\\Apps\\PsiWeb\\") do not fit NetSurf's file: URL and
colon-separated resource path handling, so NetSurf's resource: files and its
Messages are built in instead; the Psion only reads and writes the cookie
file. Usage: mkres.py NETSURF_DIR WEB_DIR > pwres.c
"""
import gzip, os, sys

ns, web = sys.argv[1], sys.argv[2]
fb = os.path.join(ns, "frontends/framebuffer/res")
files = [
    ("default.css", os.path.join(fb, "default.css")),
    ("adblock.css", os.path.join(fb, "adblock.css")),
    ("internal.css", os.path.join(fb, "internal.css")),
    ("quirks.css", os.path.join(fb, "quirks.css")),
    ("welcome.html", os.path.join(web, "res/welcome.html")),
    ("credits.html", os.path.join(fb, "credits.html")),
    ("licence.html", os.path.join(fb, "licence.html")),
]
out = sys.stdout
out.write("/* pwres.c - generated by web/mkres.py: do not edit */\n#include <stddef.h>\n#include <string.h>\n\n")
names = []
def emit(sym, data):
    out.write("static const unsigned char %s[%d] = {\n" % (sym, len(data)))
    for i in range(0, len(data), 16):
        out.write("".join("%d," % b for b in data[i:i+16]) + "\n")
    out.write("};\n")
for i, (name, path) in enumerate(files):
    data = open(path, "rb").read()
    emit("r%d" % i, data)
    names.append((name, "r%d" % i, len(data)))
msgs = open(os.path.join(fb, "Messages"), "rb").read()
if msgs[:2] != b"\x1f\x8b":
    msgs = gzip.compress(msgs, 9)
emit("messages_gz", msgs)
out.write("\nstatic const struct { const char *name; const unsigned char *data; size_t len; } res[] = {\n")
for n, s, l in names:
    out.write('\t{ "%s", %s, %d },\n' % (n, s, l))
out.write("};\n\n")
out.write("""int pwres_get(const char *name, const unsigned char **data, size_t *len)
{
	size_t i;
	for (i = 0; i < sizeof(res) / sizeof(res[0]); i++)
		if (!strcmp(res[i].name, name)) {
			*data = res[i].data;
			*len = res[i].len;
			return 0;
		}
	return -1;
}

const unsigned char *pwres_messages(size_t *len)
{
	*len = sizeof(messages_gz);
	return messages_gz;
}
""")
